import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Sibar from '@/components/Sibar'
import Display from '@/components/Display'
import Navbar from '@/components/Navbar'
import { Divider } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Parliament</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-[#0F0F1B] flex flex-col' >
        <Navbar />
        <Divider borderColor={'#232341'} />
        <div className='flex'>
        <Sibar />
        <Display  />
        </div>
             </main>
    </>
  )
}
